### ISSUE TITLE
Checksum error in the log

### ISSUE THREAD

**Issue by cdk222** [jpbarraca/pai#103]
## Alarm system
Magellan MG5050 with IP150

## Environment
Proxmox Virt Env, Debian 10, Docker Container

## Git branch
Master

## Describe the bug
Pai will run without issue on the surface but when I look in the log I can see 3 to 4 of the following message types per day. I am not sure what these mean so looking for an explanation. Pai does not disconnect and is still able to see state changes but I am just not sure what is being missed with the below ERROR.

2019-09-21 11:37:45,432 - ERROR    - PAI.paradox.hardware.spectra_magellan.panel - ChecksumError wrong checksum, read b'00', computed b'b2', message: b'0080040a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a00000200'

**Comment by jpbarraca** [comment]
Also have that. Always had, but never found what is happening. Don't know if the issue is electrical or the panel is actually outputting garbage

**Comment by yozik04** [comment]
We all have that. I am connecting via IP150 module and same garbage. So just ignore that. 2-3 messages a day. PAI just ignores them...

**Comment by cdk222** [comment]
Thanks for that - i didnt think it meant much but just wanted to make sure
