### ISSUE TITLE
Feature: Integrate with HomeAssistant

### ISSUE THREAD

**Issue by jpbarraca** [jpbarraca/pai#14]
We should integrate with HomeAssistant, either with a new interface or through the MQTT broker

**Comment by jakezp** [comment]
This would be awesome. I've purchased an IP150 yesterday, downgraded the firmware and started messing around with pai and mqtt for use in home assistant.

**Comment by yozik04** [comment]
Unfortunately it is easier not to buy this IP150 but use an arduino with a network interface or a raspberry pi. Connect it to the panel via serial. I regret that I bought IP module. I have spent to much time on it. But money is spent already. Can not return it.

Jevgeni

**Comment by jpbarraca** [comment]
If you wish to integrate your site with a monitoring company you will need a IP150. For local integration, PAI works very well.

**Comment by jakezp** [comment]
My alarm is monitored via phone / radio link. The IP150 is for local integration with home assistant. I probably should have done more research before purchasing the IP150, but I have it now. Firmware is downgraded, so I can connect to directly.

Got topics flooding to mqtt. Now I just need to figure out how to integrate with home assistant.

I do get an error in the logs when I put the alarm in 'stay' mode. But I still need to investigate and test. I'll open a new issue for this if required.

Thanks

**Comment by jpbarraca** [comment]
If you feel that there is a problem, create an issue.
Integration with HomeAssistant using MQTT should be trivial. The topics used for Homebridge can also be of use.

My purpose is to create an actual plugin. There is already one, but PAI provides a greater set of functionality over more devices and scenarios.

**Comment by jakezp** [comment]
Great. Looking forward to it.

**Comment by yozik04** [comment]
This one is solved in "dev", I think. Reopen if not.
