### ISSUE TITLE
HomeAssistant states

### ISSUE THREAD

**Issue by jakezp** [jpbarraca/pai#19]
I've made a very quick edit to add HomeAssistant MQTT Alarm Control Panel compatible states - https://www.home-assistant.io/components/alarm_control_panel.mqtt/

I've tested it and it seems to be working for me, but you will possibly have a better way of doing it. Perhaps include a check to ensure MQTT_HOMEBRIDGE_ENABLE & MQTT_HOMEASSIST_ENABLE is not set to True simultaneously and ensure it doesn't break anything else?

If you want to include it?

I know you're invesitgating a plugin, but this works.

Attached - [homeassistant-changes.txt](https://github.com/jpbarraca/pai/files/2605718/homeassistant-changes.txt)

**Comment by jakezp** [comment]
This is awesome! Thanks! I've been playing around with it and updated the commands and states as below. Home assistant does not support 'sleep' at the moment, only 'arm' and 'stay'.

Would you mind updating as below?

```
diff --git a/paradox/interfaces/mqtt_interface.py b/paradox/interfaces/mqtt_interface.py
index 348874d..2526f63 100644
--- a/paradox/interfaces/mqtt_interface.py
+++ b/paradox/interfaces/mqtt_interface.py
@@ -15,12 +15,12 @@ logger = logging.getLogger('PAI').getChild(__name__)
 PARTITION_HOMEBRIDGE_COMMANDS = dict(
     STAY_ARM='arm_stay', AWAY_ARM='arm', NIGHT_ARM='arm_sleep', DISARM='disarm')
 PARTITION_HOMEASSISTANT_COMMANDS = dict(
-    ARM_AWAY='arm', NIGHT_ARM='arm_sleep', DISARM='disarm')
+  armed_home='arm_stay', armed_away='arm', armed_sleep='arm_sleep', disarmed='disarm')

 PARTITION_HOMEBRIDGE_STATES = dict(
     alarm='ALARM_TRIGGERED', stay_arm='STAY_ARM', arm='AWAY_ARM', sleep_arm='NIGHT_ARM', disarm='DISARMED')
 PARTITION_HOMEASSISTANT_STATES = dict(
-    alarm='triggered', stay_arm='armed_away', arm='armed_away', sleep_arm='armed_home', disarm='disarmed')
+    alarm='triggered', stay_arm='armed_home', arm='armed_away', sleep_arm='armed_sleep', disarm='disarmed')

 ELEMENT_TOPIC_MAP = dict(partition=cfg.MQTT_PARTITION_TOPIC, zone=cfg.MQTT_ZONE_TOPIC,
                          output=cfg.MQTT_OUTPUT_TOPIC, repeater=cfg.MQTT_REPEATER_TOPIC,

```

**Comment by cdk222** [comment]
Hi Jakezp

Are you are to help with the Home assistant config you used to get this working (.yaml)? I had Tertiush working but cant seem to get this one going. thx

**Comment by jpbarraca** [comment]
I added the patch suggested by @jakezp 
The states will be present at  paradox/states/partition/PARTITION_NAME/current_hass
You can control the partition using the standard path: paradox/control/partition/PARTITION_NAME

**Comment by cdk222** [comment]
Maybe im having issues with the IP module interface and thus its not even getting to the stage of publishing in MQTT. At the moment I am focusing on what I am seeing on my pi when I run the script and ignoring Home Assistant.

I am connecting through the IP150 module v1.39. I am only using IP Connection details in my user.py (Not the IP Socket Interface). When I run the script the MQTT interface seems to establish ok, I get a fully established connection to the IP Module and then it connects to the Panel ok. Then all the panel information, zones, areas populates on the pi terminal followed by the the last message I receive on my pi through MQTT being:

2019-02-07 20:50:43,268 - INFO     - PAI.paradox.paradox - Connection OK

Then I do not see any further comms or status updates in MQTT on the pi regardless of whether I activate a physical zone or alarm. I tried reducing the Keep_Alive_interval but no luck. 

I did try to also enable the IP Socket Interface but received some parsing error messages and also on two occasions I saw the attached come up when I activated a zone.

Just not sure where my error is occurring and whether I need to enable the IP Socket Interface or is there another setting I have missed with the IP Module config. Also I am not sure how to increase my debug level.

Any help greatly appreciated as I think your Paradox Solution has a lot more to offer my Home Assistant setup than others I have used/seen.

Thanks
![paradox snip](https://user-images.githubusercontent.com/45811133/52416630-fde57080-2b24-11e9-8e1e-641aff4dc554.PNG)

**Comment by yozik04** [comment]
@jakezp Closing as two weeks has passed. Reopen if required.

**Comment by jakezp** [comment]
Apologies for being inactive for so long. I've been busy renovating and things are a mess and most things are unplugged at the moment. I've connected everything again and updated home assistant and pai to see if all is working now.

Seems with the new HA lovelace interface, the alarm panel has states available to be used:
arm_home
arm_away
arm_night
arm_custom_bypass

In addition to this, there is still the option to use the previous way to configure the alarm. 

I was wondering if it might not be worthwhile make the home assistant COMMANDS and STATES configurable in user.py? Then it can set to a default value in defaults.py, but configurable in user.py? This will allow future HA changes to be updated in the config file instead of requiring the code to be changed again.
