### ISSUE TITLE
Update paradox/states/partitions/Area_1/current topic on service start

### ISSUE THREAD

**Issue by jakezp** [jpbarraca/pai#21]
Is it possible to update the paradox/states/partitions/Area_1/current topic on system start?

Currently, everything is working, but home-assistant will be in a 'Unknown' state until I manually change the state (arm / disarm) the system at least once using the remote or keypad. Once I've changed the state the paradox/states/partitions/Area_1/current topic is updated and and the MQTT Alarm Panel in home-assistant functions as normal.

**Comment by yozik04** [comment]
Actually it would be good. I am also interested in having all up to date state in MQTT after script start.

**Comment by jpbarraca** [comment]
That makes sense and can be done. I will look into it

**Comment by jpbarraca** [comment]
The property "current_hass" will update the state and will be updated when the system is started. The name of the property (last part of the topic) can be changed if required.

**Comment by jakezp** [comment]
Thank you. This is working great.

**Comment by jpbarraca** [comment]
Closing as @jakezp reports that the feature is validated.

**Comment by cdk222** [comment]
@jakezp - hey are you able to share with me how you got 'current_hass' working in homeassistant. I can not get it to show a state. I used this in my .yaml

  - platform: mqtt
    state_topic: "paradox/states/partitions/Area_1/current_hass"
    name: "Paradox State"

**Comment by jakezp** [comment]
@cdk222 - I've not been working on my config for a while as we're busy with renovations and I currently have everything disconnected.

I had a quick look at my configs and seems my config is quite outdated compared to the current version.

MQTT_HOMEASSISTANT_ENABLE & MQTT_HOMEASSISTANT_SUMMARY_TOPIC options as per the defaults.py file were not yet available in the last version of my configs. So I would assume mine would default to:

MQTT_HOMEASSISTANT_ENABLE = False, which I would assume means that MQTT_HOMEASSISTANT_SUMMARY_TOPIC would have no effect.

Checking my MQTT server, I see that the last state reported by the IP150 was on "paradox/states/partitions/Area_1/current", so this is what I configured in configuration.yaml. I'd suggest getting a MQTT client to confirm which topic your status is being reported to and configuring that in configuration.yaml.

Hope it helps.

**Comment by cdk222** [comment]
Thank you for that.....if and when you have your system back up would you be able to send me the exept from your .yaml

Im still getting my head around it.......i can get my zone states fine it just the HA Alarm Control panel that im having difficulty with.

thanks again

**Comment by cdk222** [comment]
@jakezp Thank you for that.....if and when you have your system back up would you be able to send me the exerpt from your .yaml

Im still getting my head around it.......i can get my zone states fine it just the HA Alarm Control panel that im having difficulty with.

thanks again
