### ISSUE TITLE
Running PAI in a ESP8266 with MicroPython

### ISSUE THREAD

**Issue by rjduraocosta** [jpbarraca/pai#27]
Hello to all,

Could PAI be run in an ESP8266 or ESP32 with MicroPython? Does it make sence?

Thanks.

Best regards.

**Comment by jpbarraca** [comment]
It could be useful... 
Don't know if it is possible as I never executed PAI against micropython.
Do you have the time to test this environment and report what is the result?

**Comment by yozik04** [comment]
MicroPython has many limitations. Most probably you will hit some.

**Comment by jpbarraca** [comment]
I tested and the errors are too many. The fact that python construct is not available is a major issue. Thanks for the suggestion but we keep with the current minimum requirement of Python 3.5, and do not aim for micropython.

If you require a board with a small footprint, I recommend the NanoPi Neo (v1, nor the v2).

**Comment by rjduraocosta** [comment]
Hello to all,

It was just an idea. The ESP8266/ESP32 are small and they I thought it could be a possibility using Micropython.

Thanks for the reply and analisys.

**Comment by jpbarraca** [comment]
Thanks. I would like to have this, but I don't see that it will be possible. PAI has some complexity and dependencies.
