### ISSUE TITLE
feature: support command aliases?

### ISSUE THREAD

**Issue by gytisgreitai** [jpbarraca/pai#34]
What do you think about command aliases support? E.g. now you must send long commands like `partition main arm` or `partition main disarm`. What if config file could contain aliases like

```
COMMAND_ALIASES = {
 "arm" :"paritition main arm",
 "disarm" :"paritition main disarm",
<....>
}
```

what do you think?  I would make a PR for this, if this is acceptable

**Comment by yozik04** [comment]
Please explain in more details. Send where? We have multiple control endpoints.
Controlling via MQTT is definitely not that long.

**Comment by gytisgreitai** [comment]
via pushbullet or SMS - purpose to save some keystrokes on mobile keyboard

**Comment by jpbarraca** [comment]
From a usability perspective it makes sense. I like this as it is simple to be implemented and may provide a good improvement.
