### ISSUE TITLE
Locked state after alarm is triggered & disarmed from the TM70 panel

### ISSUE THREAD

**Issue by iondarie** [jpbarraca/pai#40]
Hi Guys,

So i normally arm from my phone, if the alarm is triggered on a partition it does not parse the ALARM_TRIGGERED to MQTT broker and after i DISARM from the TM70 touch keyboard the partition remains in a locked state.

It will show in homekit as being in the last state it was put in AWAY/NIGHT/STAY, no matter what command i give nothing gets passed to MQTT.

If i manually publish DISARM to the current state of the partition everything starts working again.

**Comment by yozik04** [comment]
Which panel?

**Comment by iondarie** [comment]
SP7000

**Comment by yozik04** [comment]
Did you pulled the latest master branch? We merged a big rewrite couple days ago.

**Comment by yozik04** [comment]
Please enable debug logs and try to capture the moment in logs.

`LOGGING_LEVEL_CONSOLE = logging.DEBUG` in `config/user.py`

**Comment by iondarie** [comment]
log attached

[paradox.log](https://github.com/jpbarraca/pai/files/2792039/paradox.log)

**Comment by yozik04** [comment]
Now we need @jpbarraca to help on this issue.

**Comment by iondarie** [comment]
i have gotten used to being only me and @jpbarraca around here and i forgot to delete 💃

**Comment by jpbarraca** [comment]
@iondarie send the new log to my email :)

@yozik04 I discussed this issue with @iondarie and already started fixing it last month. I will move the logic related to homebridge and homekit to a dedicated code path (new interface or at least different functions).

**Comment by yozik04** [comment]
Is this fixed?
