### ISSUE TITLE
MQTT or IP Interface Issue - Not sure

### ISSUE THREAD

**Issue by cdk222** [jpbarraca/pai#41]
Hi

I did start writing in the HomeAssistant issue section to reply to your last message but thought I should start a new section instead.

To summarise I am not sure the cause of my issue. Initially I thought I was not calling the topics correctly in my .yaml script and thus not publishing into HomeAssistant properly but now im thinking its more to do with the IP module interface and thus its not even getting to the stage of publishing in HA. 

I am connecting through the IP150 module v1.39. I am only using IP Connection details in my user.py (Not the IP Socket Interface). When I run the script the MQTT interface seems to establish ok, I get a fully established connection to the IP Module and then it connects to the Panel ok. Then all the panel information, zones, areas populate on the pi terminal followed by the the last message I receive on my pi through MQTT being:

2019-02-07 20:50:43,268 - INFO - PAI.paradox.paradox - Connection OK

Then I do not see any further comms or status updates in MQTT on the pi regardless of whether I activate a physical zone or alarm. I tried reducing the Keep_Alive_interval but no luck.

When I got no where with this I did try to also enable the 'IP Socket Interface' but received some parsing error messages and also on two occasions I saw the attached (Below) come up when I activated a zone.

Just not sure where my error is occurring and whether I need to enable the IP Socket Interface or is there another setting I have missed with the IP Module config. Also I am not sure how to increase my debug level.

Any help greatly appreciated as I think your Paradox Solution has a lot more to offer my Home Assistant setup than others I have used/seen.

Thanks

![paradox snip](https://user-images.githubusercontent.com/45811133/52417275-7862c000-2b26-11e9-9a26-df21acbdef50.PNG)

**Comment by jpbarraca** [comment]
Are you using the latest version? Main or dev? The existence of underscores suggests a different (much older) version.

You may see more information if you increase the log level to DEBUG.

**Comment by cdk222** [comment]
........as in older version of the IP150 module firmware? 

Im reluctant to update the firmware past v1.39 because i have read a lot of posts relating to issues with the later firmware versions.

Do i need to run the IP Socket Interface or should the standard IP Module connection be enough?

**Comment by jpbarraca** [comment]
As in older version of this software. I think we support all versions of IP150.
Can you provide a detailed log to my email or using keybase?
