### ISSUE TITLE
EVO 192 Got message 0 but expected 1

### ISSUE THREAD

**Issue by tlamprecht** [jpbarraca/pai#45]
**System**
My alarm system is a Paradox EVO192 and I am trying to connect with the IP150 module (Version 1.34). I have installed the PAI binding on a Rasbian Pi running Linux/Arm and Openhab2 on the same local Lan as the alarm.

**Describe the bug**
I have installed the software as explained and edited the defaults.py file with whatever made sense.  I activated the MQTT service connection as well.  It appears as if some connection is established. Authentication is successful. The panel version and firmware is read with some communication.  I then get the following error message:  ERROR:root:Got message 0 but expected 1  After that I get Initialization failed and unable to connect messages.

**To Reproduce**
1. Edit defaults.py 
2. Run: python3 run.py
3. See error message

**Logs**
PLEASE DO NOT SEND LOGS IN CLEAR TEXT AS THEY MAY CONTAIN SENSITIVE INFORMATION
If you wish to add a log (which will greatly help us), please follow the following instructions:

1. Go to https://keybase.io/encrypt
2. Write 'jpbarraca' as the recipient
3. Write your log or add a link to the log file (if using services such as dropbox).
4. Click Encrypt
5. Save the result to a text file and add it as an attachment.
[Paradox 2019-02-18.txt](https://github.com/jpbarraca/pai/files/2876265/Paradox.2019-02-18.txt)

**Comment by jpbarraca** [comment]
Thanks. We will analyse the logfile and get to you.

**Comment by yozik04** [comment]
Most probably this is wrong PASSWORD in config.

PASSWORD is 4 digit numeric.

PASSWORD = b'1234'

Same password as you type on the keypad.

**Comment by tlamprecht** [comment]
Just check - my 4 digit numeric password was correctly captured in die defaults.py file that causes the error.

**Comment by yozik04** [comment]
I have modified my password to a wrong one in configuration and got the same log as you posted. I am absolutely sure it is problem with password.
Will make some commits to improve error messages soon.

**Comment by tlamprecht** [comment]
Thank you.  I have more than one password for my panel.  I will check the other passwords as well.

**Comment by yozik04** [comment]
Try to connect with Babyware first.

User Type needs to be FullMaster (Users -> pick a user -> Security Option tab on the right)

**Comment by tlamprecht** [comment]
Thank you yozik04. I made a connection to my system. I have played around with WInLoad and BabyWare to get a better understanding of my passwords.  BabyWare insisted on a Site ID and PC password for my system.  I got BabyWare to work with Site ID 0000 and PC password 0000.  It is independent from my panel passwords.

The user.py settings that worked was PASSWORD= None.  I did confirm my FullMaster password in BabyWare, but it was the same password that caused the errors.

Thank you again for the support.  I have new question based on my outputs. My outputs contains the following message: 

"ERROR    - PAI.paradox.hardware.evo.panel - Parser for memory address (0) is not implemented. Please review your STATUS_REQUESTS setting."  

Does it relate to the STATUS_REQUEST setting in defaults.py. There are no comments next to in to guide me.  (Should I close this Issue and open a new one?)

**Comment by yozik04** [comment]
Use
`STATUS_REQUESTS = range(1, 6)   # Status requests`

**Comment by yozik04** [comment]
PASSWORD=None ????

Weird

Maybe PASSWORD=b'0000' ???

**Comment by yozik04** [comment]
You will also need for EVO:

`PARTITIONS_CHANGE_NOTIFICATION_IGNORE = ['arm_full', 'exit_delay', 'all_zone_closed', 'ready', 'stay_instant_ready', 'force_ready', 'entry_delay', 'auto_arming_engaged']`

**Comment by jpbarraca** [comment]
@yozik04 The panels seem to consider both the cases of password = unset (None) or password = value.
When the password is unset, PAI will send 0000, because when the password is actually 0000, PAI must send aaaa....

**Comment by tlamprecht** [comment]
Thank you.  I don't see the STATUS_REQUEST error anymore, but I can still not see status information on the terminal.  I can see the label information and then it stops at "Connection OK". I have disabled the mqtt connection. Can it be related to the warnings below?

WARNING  - PAI.paradox.paradox - Missing type system for event: 45.4 Special events: WinLoad in (connected)
WARNING  - PAI.paradox.paradox - Missing type system for event: 37.6 Trouble restore: Clock loss restore

**Comment by jpbarraca** [comment]
If you increase the log level to logging.DEBUG you will see lots of information about all state changes, messages, etc...

PAI is designed to provide information multiple interfaces (MQTT, Signal, Pushbullet, Pushover, GSM, etc...), but the console was not considered.

**Comment by yozik04** [comment]
I guess it is resolved now.

If not please reopen.
