### ISSUE TITLE
IP client connection problem

### ISSUE THREAD

**Issue by robissm** [jpbarraca/pai#47]
Hello,

I have enabled ip client. But when i was trying to connect with BabyWare i`ve got error. 
Basically in paradox.py it calls pause procedure which closes serial connection and exception is thrown that object is null:
 ```
File "/home/robiss/pai/paradox/interfaces/ip_interface.py", line 173, in process_client_message
    payload = self.alarm.send_wait_simple(message=message_payload[:37])
  File "/home/robiss/pai/paradox/paradox.py", line 212, in send_wait_simple
    data = self.connection.read()
  File "/home/robiss/pai/paradox/connections/serial_connection.py", line 59, in read
    recv_data = self.comm.read(read_sz)
```
I have commented connection clossing in paradoxy.py at pause function and now it works! I'm not sure why you was closing serial connection at pause function. Also i'm not good at python :)

**Comment by jpbarraca** [comment]
Hi,

Can you send me a full log?
What steps should I take to reproduce the issue.

**Comment by robissm** [comment]
[log.txt](https://github.com/jpbarraca/pai/files/2890054/log.txt)

I have attached debug log. As soon as babyware connects, serial connection disconnects. This is indicated by log line:
2019-02-21 18:04:46,316 - INFO     - PAI.paradox.paradox - Disconnecting from the Alarm Panel

This is config file. Only ip connection enabled.
[defaults.txt](https://github.com/jpbarraca/pai/files/2890075/defaults.txt)

**Comment by robissm** [comment]
sorry forgot to write how to reproduce it:
simply enable ip client
start pai
connect with babyware thought ip connection
So nothing special :)

**Comment by jpbarraca** [comment]
Thanks. We will look into this.

**Comment by robissm** [comment]
Now it works for ip client connection(i can connect/reconnect) without problems. Thanks !

**Comment by jpbarraca** [comment]
Great news. Closing.
