### ISSUE TITLE
Problem accessing panel with IP150 v4

### ISSUE THREAD

**Issue by lhubaut** [jpbarraca/pai#59]
**System**
Describe your panel model, access mode (Serial, IP150, etc..) and hardware.
MG5050 with a IP150v2 firmware v4

I adapted the pai.conf with my email and site ID (really not sure about
[lhubaut.txt](https://github.com/jpbarraca/pai/files/2989452/lhubaut.txt)
 what to put as IP_CONNECTION_PASSWORD, I tried paradox, 0000,1234, and a valid code of my alarm system, no luck)

**Logs**
(https://github.com/jpbarraca/pai/files/2989454/lhubaut.txt)

pgp attached

**Comment by lhubaut** [comment]
Hi,
Some information : 
This is due to an exception in IPConnection.connect_to_site
In fact, it seems that the JSON is badly parsed : 
logger.debug("Found module with panel serial: {}".format(module['panelSerial'])) raises the exception because, "module" is not the object but an array of object. (I have put a serial in config, but with serial, I get also exception as soon as module is used)
I need to replace module by module[0] and I get connection (except that I have a problem further with PC Password that I must investigate).
What I don't understad is why it works with others.

**Comment by lhubaut** [comment]
Second problem : it seems that PASSWORD=b'XXXX' in the config is not used. I logged its value when used and it is stil at b'0000'.... Replacing with the correct value in the code allows to connect to the panel

**Comment by jpbarraca** [comment]
It is used, but the value you put there may be different from the value sent to the panel, as it requires a slight transformation.
Can you provide a log with this evidence?

**Comment by lhubaut** [comment]
For the connection your change is working .
For the PASSWORD : I saw in a thread that it should be added, but in fact, it was in the config sample but later (not in the IP config), so mine was overloaded, everything is ok now

Thanks

**Comment by jpbarraca** [comment]
Great. Closing
