### ISSUE TITLE
Cannot import name 'user'

### ISSUE THREAD

**Issue by radokristof** [jpbarraca/pai#66]
**System**
IP150 panel

**Describe the bug**
Hi everyone! I'm trying to migrate my system to this interface. However I'm facing issues even with starting it. I'm trying to use it with Docker. I have modified the conf file and mounted it to the appropriate file in the container.
However starting the container produces this error:

`Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from paradox import main
  File "/opt/paradox/paradox/main.py", line 16, in <module>
    from config import user as cfg
ImportError: cannot import name 'user'
`
I don't really know what the problem can be. Maybe someone can help?

Thanks!

**Comment by radokristof** [comment]
Also where the logs stored in the container? What is the easiest way to have a look at the logs? (But I assume that there are not too much, because this happens right on startup).

**Comment by radokristof** [comment]
I was able to get it running manually. However it would be great to have it in Docker.
Also I get a lot of connection error in the log now, is this normal? (codec can't decode byte... and then unable to connect, but after it connects).
Secondly, I can only see paradox/events and paradox/interface/MQTTinterface topic in MQTT, all others are missing.

Hope someone can help me out...

**Comment by yozik04** [comment]
What panel it is about?

**Comment by radokristof** [comment]
It is an SP5500 (which is also detected correctly by this script as I can see it in the logs).

**Comment by radokristof** [comment]
Also I don't know where I have to set the `Panel User Code` which I have to enter when I want to access the module. I can only set the `Module Password`.

**Comment by yozik04** [comment]
Do you have any special symbols in partition/zone names?

**Comment by radokristof** [comment]
What translates here as special characters? I have spaces and dots in some of the names but nothing unusual except these (only English characters)

**Comment by yozik04** [comment]
Then you need to send full debug log to @jpbarraca so he can check what is wrong.

**Comment by jpbarraca** [comment]
Yes. Please use gitter or my email

**Comment by radokristof** [comment]
I have sent a private message on Gitter

**Comment by yozik04** [comment]
Docker **jpbarraca/pai:dev** should work, I think.

**Comment by yozik04** [comment]
`docker run -v <host_conf_path>:/etc/pai:ro -v <host_log_path>:/var/log/pai:rw jpbarraca/pai:dev`

**Comment by yozik04** [comment]
when you run first time it should create default **pai.conf** in <host_conf_path>

**Comment by radokristof** [comment]
Thanks, I will use it that way in my final config (Docker). However now the second problem is more important, because it will happen anyway, so we have to fix it that one first (@jpbarraca is currently looking into my issue). Hope someone else will also benefit from this problem...

**Comment by yozik04** [comment]
Was it resolved?

I see @jpbarraca did some commits about label encoding.

**Comment by radokristof** [comment]
Yes, using alternative encoding (latin2) it works. I haven't tried it with Docker yet, but I suppose it works there also.

**Comment by yozik04** [comment]
Great!

**Comment by radokristof** [comment]
It is working with Docker too, except 1 thing... It won't publish to MQTT. I can see it in the log that zone states changes, but not in MQTT...
Running manually from Python with the same config (the same config file is added to Docker as a volume), it works. What I'm missing?
