### ISSUE TITLE
[question] Possibility to fully replace IP150

### ISSUE THREAD

**Issue by kobuki** [jpbarraca/pai#71]
Please excuse me if it's not the proper place to ask but I don't really see another contact option, like a forum or chat. What I'd like to know if it's possible to fully replace an IP150 with a device with pai installed. Why do I ask? Our panel is connected to a local security company equipped with Paradox IP receivers for supervision and quick onsite visit if necessary. They don't care about the technology, the system is owned by us, so I was wondering what would it take to connect to their receiver. What protocol or software could be used? IIRC one of their installers said the receiver is using an TCP/IP-based variant of the Contact ID standard protocol. Does anyone have info on the above?

**Comment by jpbarraca** [comment]
AFAIK we have no information about this process or the protocol used. The purpose of PAI was never to replace an official product, only to allow the integration with custom systems in our sites.

**Comment by kobuki** [comment]
Hmm, yes, I understand that. Apparently, though, the protocol used is indeed CID (Ademco Conatct ID), and it uses a pretty simple, fixed ASCII reporting format, through either plain TCP/IP or TLS. There's an [interesting project](https://github.com/schmupu/ioBroker.contactid) on Github that implements the other end, ie. the receiver as a Node service. I might play around with that a bit later to see if I can push reports to that service, specifying a second reporting IP in the panel. Pai could provide the necessary events via MQTT, and a small service could forward those events in the proper format to an active receiver. (It's a completely different project, of course.)

**Comment by jpbarraca** [comment]
The events are already published to the MQTT bus using the topic "paradox/events"

**Comment by kobuki** [comment]
Yes, I know that. I've found almost all the required bits to make a service that can send the events to a receiver. A missing bit is the registration protocol that registers a panel to the IP receiver. It might require a genuine Paradox device serial (panel, IP module, etc), though, so something like an IP150 must do the initial step of registration (required only once at installation), then the communication could theoretically go on without it. This makes my idea moot, but just almost, since having full control over all components can be desirable.
