### ISSUE TITLE
Example mqtt for operating a pgm output?

### ISSUE THREAD

**Issue by psyciknz** [jpbarraca/pai#81]
Is there an example for the mqtt topic and payload that is used for operating a pgm output?  I have one called garage_door.

As far as I can tell I have to send and `on` to `paradox/control/outputs/Garage_Door` is that right?
Given it's a garage door, I think `on` opens and closes it, and I have a separate sensor that knows whether it's open or closed.

**Comment by jpbarraca** [comment]
PGM control is supported for MG/SP panels.
You can send on, off, on_override, off_override and pulse. With the exception of the pulse command, which triggers a on and off, the remaining commands will be sent to the panel.

**Comment by psyciknz** [comment]
Yes but did I have the topic right?  The wiki was a little unclear if I just ended it on the name of the pgm item.  It is a different format to the input zones which are states/zonename/fieldname

**Comment by jpbarraca** [comment]
Thanks for the feedback. I updated the wiki to correct the description.
