### ISSUE TITLE
UTF-8 encoding

### ISSUE THREAD

**Issue by jooka1978** [jpbarraca/pai#82]
Hi,

Just to help to improve the project.
In my config utf-8 is enabled: LABEL_ENCODING = 'utf-8'.
My BabyWare is set to Hungarian, so all the not used zones are "Zóna 020, Zóna021 etc ".
When PAI sarts I get tis messages:
2019-05-23 23:49:46,674 - WARNING  - PAI.paradox.hardware.panel - Unable to properly decode label b'NappaliErk\x96ly' using the utf-8 encoding.
                     Specify a different encoding using the LABEL_ENCODING configuration option.
2019-05-23 23:49:46,746 - WARNING  - PAI.paradox.hardware.panel - Unable to properly decode label b'Z\x8dna 15' using the utf-8 encoding.
                     Specify a different encoding using the LABEL_ENCODING configuration option.
Should I use something else instead of UTF-8?

Thanx

**Comment by jpbarraca** [comment]
Hi,

Yes, you can try a different encoding such as "ISO 8859-16"

**Comment by radokristof** [comment]
@jooka1978 Hi, I'm also from Hungary. You can set alternative encoding, I'm using latin2, it works fine with that..

**Comment by jooka1978** [comment]
Hi Kristof :-) yes, latin2 worsk great, thanks.

**Comment by jpbarraca** [comment]
Closing as it is working.
