### ISSUE TITLE
Current topic is not valid when using Stay_Arm

### ISSUE THREAD

**Issue by radokristof** [jpbarraca/pai#83]
**System**
IP150

**Describe the bug**
When using Stay_Arm, the /current state topic is gets the STAY_ARM payload right after (or few seconds after) issuing a command (no matter if it is done via software - MQTT or directly on the panel), not when the exit_delay finishes.
Away_Arm however works as it should. The /current state topic only gets the AWAY_ARM payload when the exit_delay finished.

**Comment by radokristof** [comment]
Changes in 167af336092f9015673d16f5151c87bfeed077ae hafly fixed this.
Now the arm_stay changes after exit delay expired, but to away_arm not to stay_arm

**Comment by jpbarraca** [comment]
Can you detail this?

**Comment by yozik04** [comment]
I think this is how alarm does it. Am I right?
It sets **arm_stay** or **arm_sleep** flag and "exit_delay" flag. When exit delay finishes is sets "arm" flag

**Comment by yozik04** [comment]
Please collect log from MQTT.
`$ mosquitto_sub -u user -P pass -v -t paradox/#`

**Comment by radokristof** [comment]
Sorry I had busy weeks, didn't had time to work on this. I will collect the log in the next days.
Basically what happens is that when I send `arm_stay` it immediately sets all states to `arm_stay`, not after exit_delay is finished. With away_arm it works as it should, only setting after the exit_delay is finished.

**Comment by jpbarraca** [comment]
Hi. Thanks for the report.
Can you send a log if the mqtt states?

**Comment by yozik04** [comment]
@radokristof For your understanding:

![arming](https://user-images.githubusercontent.com/2420038/63587171-e135f500-c5ab-11e9-9903-89384ee7e5ea.png)

**Comment by yozik04** [comment]
🤦‍♂ entry_delay -> exit_delay. Fixed in above.

**Comment by yozik04** [comment]
Let's continue in #90
