### ISSUE TITLE
We are not sure what panel you have (product_id: {})

### ISSUE THREAD

**Issue by MiroMutti** [jpbarraca/pai#85]
I'm trying to connect SP65 version 5.14 via IP150. It shows "Found Panel SP65 version 5.20 build 0""and ask to make an issue. 
![Capture](https://user-images.githubusercontent.com/32312310/59148833-3d11c880-8a16-11e9-9966-1a01562ae938.JPG)

**Comment by jpbarraca** [comment]
Welcome 😃
Please enable full debug, including packet and message dumps and send it to us.
Use your gitter or my email jpbarraca gmail. 

Thanks !

**Comment by yozik04** [comment]
@jpbarraca Just add product id 27 to SP/MG branch. I think that will do.

**Comment by yozik04** [comment]
@MiroMutti Please try dev branch

**Comment by MiroMutti** [comment]
Hello,

thank you for the help, everything works perfect! 🙂

**Comment by yozik04** [comment]
Great!
