### ISSUE TITLE
Support password of 6 digits (EVO192)

### ISSUE THREAD

**Issue by bwibwi13** [jpbarraca/pai#88]
Hello,

I am trying to connect my EVO192 with IP150 (>v4.0) to my MQTT broker.
Things seems to work quite well until connecting to panel:
>  INFO     - PAI.paradox.connections.ip_connection - Authentication Success. Panel version 20, firmware: 4.48, serial: 71083af6
>INFO     - PAI.paradox.connections.ip_connection - Session Established with IP Module
>INFO     - PAI.paradox.paradox - Connecting to panel
>INFO     - PAI.paradox.paradox - Initiating communication
>INFO     - PAI.paradox.paradox - Found Panel EVO192 version 6.144 build 5
>INFO     - PAI.paradox.paradox - Starting communication
>ERROR    - PAI.paradox.paradox - Connect error
>Traceback (most recent call last):
>  File "/home/osmc/git/pai/paradox/paradox.py", line 153, in connect_async
>    result = await self.panel.initialize_communication(reply, cfg.PASSWORD)
>  File "/home/osmc/git/pai/paradox/hardware/evo/panel.py", line 121, in initialize_communication
>    encoded_password = self.encode_password(password)
>  File "/home/osmc/git/pai/paradox/hardware/panel.py", line 115, in encode_password
>    raise(Exception("Password length must be equal to 4. Got {}".format(len(password))))
>Exception: Password length must be equal to 4. Got 6
>ERROR    - PAI - Unable to connect to alarm

I tried to change the encode_password() function to support 6 digits but I don't really know what it is trying to compute in this function.
If I generate an encoded password of 3 bytes, the connection logic rejects the password that is expected to be of 2 bytes.

## Feature description
The guy that installed my alarm recommended me to use 6-digit alarm code for more security.
Can we extended the current implementation to support this?

Thanks a lot for your help.

**Comment by yozik04** [comment]
How do you connect? via SWAN? or locally?

**Comment by yozik04** [comment]
`encode_password` function change itself won't help. There is only 2 bytes placeholder in the protocol `InitializeCommunication`. I have no idea how it can send more than 2 bytes.
Actually I can capture that on my system... Will try next days.

**Comment by bwibwi13** [comment]
@yozik04 Thanks for the quick response :)

I must say that I am not sure if I connect via Swan or locally.
I am on the LAN and I would prefer to connect locally.
But I have provided the Swan information in the config file.
How do I select from one or the other?

Thanks a lot for your help :)

**Comment by yozik04** [comment]
If you have provided IP_CONNECTION_SITEID and IP_CONNECTION_EMAIL then it will use SWAN.
I am not sure if local connection was fully enabled again in latest 4.x IP150 firmwares...
I have downgraded mine to 1.32 to use it locally.

**Comment by yozik04** [comment]
Can you try password with first 4 digits from your 6 digit password please? If it will work it will be 🤦‍♂

**Comment by yozik04** [comment]
Ahh. I am wrong. This is PC Password. It is not connected anyhow with user passwords. It is separate password. In Babyware: Right click on panel -> properties -> PC Communication -> PC Communication Tab.

**Comment by yozik04** [comment]
It can only be 4 digits.

**Comment by yozik04** [comment]
Fixed description in config file: b1cae7db994b6910191083bc6892e9edd3402821

**Comment by yozik04** [comment]
I marked it "invalid" as you do not need 6 digit password to use PAI. PC password is 4 digits max. And it looks like it can be digits from [0-9a-f]. According to babyware pc password input field.

**Comment by bwibwi13** [comment]
Thanks a lot for your fast response and analysis.
Sorry I got confused between the various passwords.
I also take the opportunity to thank you for this great repository :)

**Comment by yozik04** [comment]
So you got connected?

**Comment by yozik04** [comment]
Great to hear that somebody likes the effort :)

**Comment by bwibwi13** [comment]
@yozik04 sorry for the delayed response, I did not have time to work on this in the last days.
Yes, I did connect once I used the appropriate password. Thanks again for all your help.
I did not have time yet to take a closer look at the results.
I could just see some warnings on messages not supported.
I'll take a closer look and let you know.
Cheers :)

**Comment by bwibwi13** [comment]
I just realized that the issue was not yet closed.
As I can connect to the panel with a 4 digit password as expected in the protocol, this bug can be closed.
