### ISSUE TITLE
No handler for message 5

### ISSUE THREAD

**Issue by lhubaut** [jpbarraca/pai#89]
Hi,
In my logs I get many ERROR like 

`2019-08-13 05:41:43,476 - ERROR    - PAI.paradox.lib.async_message_manager - No handler for message 5
Detail: Container:
    fields = Container:
        data = b'R\x00\x80\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'... (truncated, total 36)
        value = Container:
            po = Container:
                command = 5
                status = Container:
                    reserved = False
                    alarm_reporting_pending = False
                    Winload_connected = True
                    NeWare_connected = False
            validation = 128
            address = 5
            data = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'... (truncated, total 32)
        offset1 = 0
        offset2 = 36
        length = 36
    checksum = b'\xd7' (total 1)
` 
Is it a problem or on purpose? (I use a IP150 v4)

**Comment by yozik04** [comment]
It usually goes in pair with "No reply to status request". How many is many?

**Comment by lhubaut** [comment]
Hi, 
It depends, but it is often every 5, 10 or 15 minutes

I didn't see errors with reply status
I put a decrypted log showing those messages
[message5.txt](https://github.com/jpbarraca/pai/files/3496728/message5.txt)

**Comment by yozik04** [comment]
You should not worry about that. It is OK. One status request failure in 5 or 10 minutes is nothing... PAI makes 5 status (pages) requests every 10 seconds.

**Comment by lhubaut** [comment]
thank you for your response.

**Comment by jpbarraca** [comment]
Also, if there are too many failures, it will reconnect and recover from the error.
