### ISSUE TITLE
Homekit interface arm state

### ISSUE THREAD

**Issue by jpbarraca** [jpbarraca/pai#9]
Reported by @iondarie
Arming with homekit in NIGHT mode will issue a sleep and then a away arm.

**Comment by iondarie** [comment]
ok so after more testing here are my exact steps.

started -> mosquitto_sub -t paradox/states/partitions/Etaj/current
started -> sudo systemctl start pai.service

- On PAI.paradox - Connection OK the mqtt topic got 2x DISARMED
- On PAI.mqtt_interface - message topic=paradox/control/partitions/Etaj/, payload=NIGHT_ARM the mqtt topic got NIGHT_ARM after ~20 seconds it gets AWAY_ARM
- On PAI.mqtt_interface - message topic=paradox/control/partitions/Etaj/, payload=DISARM the mqtt topic got 2 x DISARMED
- On PAI.mqtt_interface - message topic=paradox/control/partitions/Etaj/, payload=STAY_ARM the mqtt topic got STAY_ARM after ~20 seconds it gets AWAY_ARM
- On PAI.mqtt_interface - message topic=paradox/control/partitions/Etaj/, payload=DISARM the mqtt topic got 2 x DISARMED
- On PAI.mqtt_interface - message topic=paradox/control/partitions/Etaj/, payload=AWAY_ARM the mqtt topic got AWAY_ARM and it works properly

Hope you can understand what i am trying to explain. Or even better see bellow or the attached log.


-----------------PAI------------------
PAI.paradox - Connection OK
PAI.mqtt_interface - message topic=paradox/control/partitions/Etaj/, payload=NIGHT_ARM
PAI.mqtt_interface - message topic=paradox/control/partitions/Etaj/, payload=DISARM
PAI.mqtt_interface - message topic=paradox/control/partitions/Etaj/, payload=STAY_ARM
PAI.mqtt_interface - message topic=paradox/control/partitions/Etaj/, payload=DISARM
PAI.mqtt_interface - message topic=paradox/control/partitions/Etaj/, payload=AWAY_ARM
PAI.mqtt_interface - message topic=paradox/control/partitions/Etaj/, payload=DISARM

-----------------MQTT------------------
DISARMED
DISARMED
NIGHT_ARM
AWAY_ARM
DISARMED
DISARMED
STAY_ARM
AWAY_ARM
DISARMED
DISARMED
AWAY_ARM
DISARMED

[paradox.log](https://github.com/jpbarraca/pai/files/2496837/paradox.log)

**Comment by jpbarraca** [comment]
@iondarie Can you check this?

**Comment by iondarie** [comment]
Ill can test everything in a few minutes except the triggered state

**Comment by iondarie** [comment]
It seems to work ok, please close the issue.

Thank you,
