### ISSUE TITLE
Can't connect from USB307

### ISSUE THREAD

**Issue by b0c1** [jpbarraca/pai#95]
## Alarm system
EVOHD, Serial (using USB307 /dev/ttyUSB0 )

## Environment
OrangePI, Python 3.7.3

## Git branch
Which Git branch you use. Did you tried "dev" branch? Please try before posting.

## Describe the bug
I can't connect to the panel. If I install virtualhere and forward /dev/ttyUSB0 to my pc, I can connect to the panel with password 0000, but I can't connect from pai.

## To Reproduce
```python3 run.py```

## Logs
```
2019-08-30 21:54:39,449 - INFO     - PAI.paradox.paradox - Found Panel EVOHD version 7.17 build 6
2019-08-30 21:54:39,450 - INFO     - PAI.paradox.paradox - Starting communication
2019-08-30 21:54:39,586 - INFO     - PAI.paradox.hardware.evo.panel - Initializing communication
2019-08-30 21:54:39,607 - ERROR    - PAI.paradox.paradox - Got ERROR Message: Invalid PC Password
```

**Comment by yozik04** [comment]
It is clearly stated what is wrong in the log.

**Comment by yozik04** [comment]
From PC you try with Babyware or what?

**Comment by yozik04** [comment]
Damn. Sorry, you try via USB. Ignore above.
```
PASSWORD = b'0000'   			# PC Password. Set to None if Panel has no Password.
```

Did you tried setting to None?

**Comment by b0c1** [comment]
> 
> 
> From PC you try with Babyware or what?

in PC it's 0000... I will try to None

**Comment by yozik04** [comment]
If you used something other than Babyware and it connects you with 0000 pass. I want a serial capture of that. 😄

**Comment by b0c1** [comment]
None working correctly... thanks
