### ISSUE TITLE
MQTT Dash Cannot subscribe

### ISSUE THREAD

**Issue by segald88** [jpbarraca/pai#97]
## Alarm system
I have an MG5050 with IP150 on the latest version
## Environment
MQTT and PAI running on the same Pi 3b

## Question
I am able to connect to my panel and receive MQTT message on the broker but only if I sub to '#'
I am trying to connect MQTT Dash using metrics/exchange/pai but never receive it.
Can you please assist
I can see both partitions are being learnt
Thanks
Dani

**Comment by jpbarraca** [comment]
Glad to ear :)
